language: scala

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sbt"
  - "$HOME/.ivy2"

scala:
- 2.11.8

jdk:
- oraclejdk8

script:
- sbt clean coverage test package
# Trick to avoid unnecessary cache updates
- find $HOME/.sbt -name "*.lock" | xargs rm

notifications:
  slack:
    rooms:
      - $SLACK_TOKEN
    on_success: change
    on_failure: always

after_success:
  - >
      sbt coveralls &&
      sh "$TRAVIS_BUILD_DIR/travis-ci-bintray-credentials.sh" &&
      sbt publish